name: Deploy Automático a mi VM
on:
  push:
    branches: [ main ] # Se activa cada vez que hagas push a la rama main

jobs:
  deploy:
    runs-on: self-hosted # Esto le dice a GitHub que use tu VM de Ubuntu
    steps:
      - name: Descargar el código de GitHub
        uses: actions/checkout@v4

      - name: Levantar la App con Docker
        run: |
          docker compose up -d --build
